#!/bin/bash

if [ -z "$1" ]; then
    selected=$(find ~/work -mindepth 1 -maxdepth 2 -type d | fzf)
else 
    selected="$1"
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected")
tmux_running=$(pgrep tmux)

if [[ $selected_name == .* ]]; then
    selected_name="${selected_name#.}"
fi

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else 
    tmux switch-client -t $selected_name
fi

